# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Kiwami defaults (but don't edit these directly!)
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/bindings/media.conf
source = ~/.config/hypr/config/bindings/clipboard.conf
source = ~/.config/hypr/config/bindings/tiling-v2.conf
source = ~/.config/hypr/config/bindings/utilities.conf
source = ~/.config/hypr/config/envs.conf
source = ~/.config/hypr/config/looknfeel.conf
source = ~/.config/hypr/config/input.conf
source = ~/.config/hypr/config/windows.conf
source = ~/.config/hypr/config/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.config/hypr/config/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
