# App-specific tweaks
source = ~/.config/hypr/config/apps/1password.conf
source = ~/.config/hypr/config/apps/bitwarden.conf
source = ~/.config/hypr/config/apps/browser.conf
source = ~/.config/hypr/config/apps/hyprshot.conf
source = ~/.config/hypr/config/apps/localsend.conf
source = ~/.config/hypr/config/apps/pip.conf
source = ~/.config/hypr/config/apps/qemu.conf
source = ~/.config/hypr/config/apps/retroarch.conf
source = ~/.config/hypr/config/apps/steam.conf
source = ~/.config/hypr/config/apps/geforce.conf
source = ~/.config/hypr/config/apps/moonlight.conf
source = ~/.config/hypr/config/apps/system.conf
source = ~/.config/hypr/config/apps/telegram.conf
source = ~/.config/hypr/config/apps/typora.conf
source = ~/.config/hypr/config/apps/terminals.conf
source = ~/.config/hypr/config/apps/walker.conf
source = ~/.config/hypr/config/apps/webcam-overlay.conf
